### ISSUE TITLE
Implementación de webhooks

### ISSUE THREAD

**Issue by paulinabustos** [mxabierto/validadora#7]
Quel permita una orientación a eventos de la validadora.

**Comment by rodowi** [comment]
Interesante. Entonces la validadora estará esperando un POST con resultados de los validadores?

**Comment by zoek1** [comment]
@rodowi se pensaba más para outgoing webhooks, similar a como lo hace [Slack](https://api.slack.com/outgoing-webhooks). Esto para registrar endpoints y devolver respuesta inmediatamente que se terminen las validaciones, en vez de obtener el id y que los clientes estén consultando cada 50 seg el estado de la validación.
Aunque se puede ampliar a tener incoming webhooks para el schedunlig de tareas, actualización  de validadores, etc.

**Comment by rodowi** [comment]
¿qué endpoints se necesitan para conectarse con ADELA?

**Comment by rodowi** [comment]
Ejemplos de lo que se necesita para webhooks
- https://developer.atlassian.com/jiradev/jira-apis/webhooks?continue=https%3A%2F%2Fdeveloper.atlassian.com%2Fjiradev%2Fjira-apis%2Fwebhooks&application=dac
- https://help.github.com/articles/about-webhooks/

**Comment by rodowi** [comment]
1. ADELA debe conseguir permiso para crear webhooks en Validadora
2. ADELA debe registrar un webhook en Validadora: debe definir endpoint de recepción de mensajes
3. La Validadora debe poder asociar procesos de validación a un webhook para comunicar los resultados

**Comment by rodowi** [comment]
Después de la llamada, esto se descompone en #13 #14 #15
